# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Portfolio of Bartłomiej Stanasiuk
url: "https://bstanasiuk.github.io"
baseurl: ""
locale: "en-US"
email: bartlomiej.stanasiuk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the portfolio and personal website of a game developer Bartłomiej Stanasiuk.
#twitter_username: username
github_username: bstanasiuk
minimal_mistakes_skin: "dark"
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Bartłomiej Stanasiuk"
  avatar : "/assets/images/photo.jpg"
  bio    : "A passionate software engineer interested in web and game development in .NET technologies.
  <br><br><b>Education:</b>
  <br>BSc/MSc in Computer Science at Wrocław University of Technology
  <br><br><b>Technical Skills:</b>
  <br>C#, Java, CSS/HTML/JavaScript, SQL, RDBMS, O/RM, JSON, ASP.NET Core, Unity3D, Spring Boot, Git, Github, SVN, Visual Studio, JetBrains IDEs"
  links:
    - label: "bartlomiej.stanasiuk@gmail.com"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:bartlomiej.stanasiuk@gmail.com"

footer:
  links:
    - label: "Unity Certified Developer"
      icon: "fas fa-fw fa-certificate"
      url: "https://www.youracclaim.com/badges/62f1b363-a695-4119-b71b-a6023c32b9f5"
    - label: "Apps on Play Store"
      icon: "fas fa-fw fa-play"
      url: "https://play.google.com/store/apps/developer?id=BStanasiuk"
    - label: "Apps on Itch.io"
      icon: "fas fa-fw fa-gamepad"
      url: "https://bstanasiuk.itch.io/"
    - label: "GitHub Profile"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bstanasiuk"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
